MOD_ACTING_PATTERNS = [
    r"\[mod\]",
    r"\[moderator\]",
    r"as a mod\b",
    r"as a moderator",
    r"removed by mod",
    r"mod here\b",
    r"moderator here",
    r"mod action",
    r"mod note",
    r"locking this",
    r"this post (has been|is being) removed",
]

COMMUNITY_CALL_PATTERNS = [
    r"@mod\b",
    r"@mods\b",
    r"mod please",
    r"mod should",
    r"mod intervene",
    r"mods please",
    r"mods should",
    r"mod.*intervene",
    r"report.*pump",
    r"this is (a )?pump and dump",
    r"pump and dump (warning|alert|scheme)",
    r"calling.*mods",
    r"someone.*report this",
    r"flag(ging)? (this|as) pump",
    r"do not invest based on this",
    r"this (looks|smells) like a pump",
    r"coordinated pump",
    r"paid (shill|promotion|post)",
    r"mods.*remove",
]
