import type { TickerData } from "../types/Dashboard";

export const dashboardMapper = (data: any): TickerData[] => {
  return data.map((item: any) => ({
    stockName: item.ticker,
    mentions: item.mentions,
    averageSentiment: item.avg_sentiment,
    finalScore: item.final_score,
    baseFinalScore: item.base_final_score,
    preMultiplierScore: item.base_final_score,
    catalystMultiplier: item.catalyst_multiplier,
    crossSubredditMultiplier: item.cross_subreddit_multiplier,
    subredditMultiplier: item.subreddit_multiplier,
    userCredibilityMultiplier: item.user_credibility_multiplier,
    postQualityMultiplier: item.post_quality_multiplier,
    socialConvictionMultiplier: item.social_conviction_multiplier,
    credibilityMultiplier: item.credibility_multiplier,
    evidenceQualityMultiplier: item.evidence_quality_multiplier,
    tickerMentionDensityMultiplier: item.ticker_mention_density_multiplier,
    engagementMultiplier: item.engagement_multiplier,
    accountAgeMultiplier: item.account_age_multiplier,
    karmaMultiplier: item.karma_multiplier,
    authorDiversityMultiplier: item.author_diversity_multiplier,
    combinedSignalMultiplier: item.combined_signal_multiplier,
    subredditsMentioningTicker: item.subreddits_mentioning_ticker,
    subredditMentions: item.subreddit_mentions,
    topContexts: item.top_contexts,
    price: item.price,
    changePercent: item.change_percent,
    marketCap: item.market_cap,
    fiftyTwoWeekHigh: item.fifty_two_week_high,
    fiftyTwoWeekLow: item.fifty_two_week_low,
    volume: item.volume,
    analystTarget: item.analyst_target,
    recommendation: item.recommendation,
    sector: item.sector,
    description: item.description,
    name: item.name,
    symbol: item.symbol,
    shortName: item.short_name,
    industry: item.industry,
    website: item.website,
    logoUrl: item.logo_url,
    exchange: item.exchange,
    currency: item.currency,
    country: item.country,
    city: item.city,
    state: item.state,
    zip: item.zip,
    phone: item.phone,
    email: item.email,
    ceo: item.ceo,
    founded: item.founded,
    employees: item.num_employees,
    tags: item.tags,
    similar: item.similar,
    related: item.related,
    stats: item.stats,
    financials: item.financials,
    news: item.news,
    events: item.events,
    earnings: item.earnings,
    dividends: item.dividends,
    splits: item.splits,
    stockSplits: item.stock_splits,
    stockDividends: item.stock_dividends,
  }));
};
